version: "3.9"

services:
  user-service:
    build: ./user-service
    ports:
      - "50051:50051"

  order-service:
    build: ./order-service
    ports:
      - "50052:50052"

  bff:
    build: ./bff
    ports:
      - "50050:50050"
    depends_on:
      - user-service
      - order-service
